name: vanelliapp
version: 1.0.0+1
publish_to: none
description: Gerenciador de Eventos.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^1.8.0
  firebase_storage: ^10.0.7
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.5
  firebase_database: ^8.1.0
  google_sign_in: ^5.2.1
  validatorless: ^1.2.1
  flutter_masked_text2: ^0.9.1
  get: 4.3.8
    # Google icon
  font_awesome_flutter: ^9.1.0
  table_calendar: ^3.0.3
  syncfusion_flutter_calendar: ^19.3.54
  syncfusion_localizations:
  im_stepper: ^0.1.3



dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/firebase_logo.png
  uses-material-design: true

